database:
    adapter: mysql2
    user: root
    host: localhost
    passwd: 123
    database: elvenhut_database
blog:
    title: ElvenHut | A blog engine for personal using
    url: www.example.com
    site_name: ElvenHut
    site_description: A blog engine for personal using
    admin_name: admin
    admin_passwd: admin
social:
    gplus:
    github: https://github.com/halfelf/ElvenHut
basic_setting:
    # <code> style options: public/css/highlight/(.*).css
    code_style: default
    post_each_page: -1
    show_comment: yes
    show_author: yes
