database:
    adapter: mysql2 # or "sqlite"
    user: root  # mysql2 required
    host: localhost # mysql2 required
    passwd: 123 # mysql2 required
    database: elvenhut_database
blog:
    title: ElvenHut | A blog engine for personal using
    url: www.example.com
    site_name: ElvenHut
    site_description: A blog engine for personal using
    admin_name: admin
    admin_passwd: admin
    email: 
social:
    gplus:
    github: https://github.com/halfelf/ElvenHut
basic_setting:
    # <code> style options: public/css/highlight/(.*).css
    code_style: default
    reply_notificate: yes  # send email when got a reply. [Note] Make sure your postfix(or others smtp server is running).
    post_each_page: -1
    show_comment: yes
    use_disqus: no
    disqus_shortname: 
rakismet:
    use: no
    key:    #required. signup at http://akismet.com to get a key.
    url:    #required. may same as host
    host: rest.akismet.com  #as default
